#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ceph-deploy
Version  : 1.5.31
Release  : 2
URL      : https://pypi.python.org/packages/source/c/ceph-deploy/ceph-deploy-1.5.31.tar.gz
Source0  : https://pypi.python.org/packages/source/c/ceph-deploy/ceph-deploy-1.5.31.tar.gz
Summary  : Deploy Ceph with minimal infrastructure
Group    : Development/Tools
License  : MIT
Requires: ceph-deploy-bin
Requires: ceph-deploy-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
========================================================
ceph-deploy -- Deploy Ceph with minimal infrastructure
========================================================

%package bin
Summary: bin components for the ceph-deploy package.
Group: Binaries

%description bin
bin components for the ceph-deploy package.


%package python
Summary: python components for the ceph-deploy package.
Group: Default

%description python
python components for the ceph-deploy package.


%prep
%setup -q -n ceph-deploy-1.5.31

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ceph-deploy

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
